### PR TITLE
Update sunburst

### PR DESCRIPTION
**Pull request by angelanicholas**
- first pass at a Victory sunburst component (still needs some standardizing/victory-ifying)
- webpack bundle visualizer demo

screen shot 2017-06-05 at 2 01 50 pm

### CODE REVIEW

**Comment by boygirl** [comment]
@angelanicholas this is looking great. I would love to eventually get it working with Victory's event system, animations, and give it replaceable rendered components like other Victory stuff, but I don't think it makes sense to block on any of that at the moment.

**Comment by kenwheeler** [comment]
Whoah

**Comment by angelanicholas** [comment]
@boygirl I added events, animation, and replaceable rendered components! Ready for re-review

**Comment by boygirl** [comment]
@angelanicholas this is looking great!! The only outstanding major difference I see between this and other chart types at this point is labels. Are they appropriate for sunbursts? Tooltips?

I've added a bunch of label helpers for polar charts, that I _think_ can be re-used here. That probably makes sense to tackle in a separate PR though. I also got `VictoryVoronoiContainer` working for polar charts. Maybe we can support that here too. I think that would be awesome for hovering tiny slices.

Anyway. I vote for merging this and addressing those features separately. I'm also happy to take on the voronoi container work if you'd like, since it would involve some changes to `VictoryVoronoiContainer`

**Comment by angelanicholas** [comment]
@boygirl I thought about labels, but since sunbursts typically are only used for relatively dense visualizations, labels didn't seem very functional unless only shown one at a time on arc hover. Adding a some kind of optional subcomponent for displaying details on hover is probably a suitable thing to incorporate though (currently it's just in the demo)... will do! I'll merge this and add hover details into a followup PR

**Pull request merged**
